### ISSUE TITLE
access to tutorial and documentation site for the older autojsoncxx project

### ISSUE THREAD

**Issue by cbuchner1** [netheril96/StaticJSON#16]
Hi,

these links to the autojsoncxx web page and tutorials no longer work, even after replacing the autojsoncxx part of the URL with StaticJSON

​https://netheril96.github.io/autojsoncxx/ 
http://netheril96.github.io/autojsoncxx/tutorial/ 

this was a very good reference for users of the older autojsoncxx project. Can you reinstate those web pages (maybe marking them as deprecated). The examples given on the pages were helpful.

Alternatively, the pages could be checked into the autojsoncxx branch.

Christian

**Comment by netheril96** [comment]
The old site is now back online.

**Comment by netheril96** [comment]
By the way, it would be nice if you give a star to this project.

**Comment by netheril96** [comment]
In addition, the documentation is actually within the `docs` directory in the `autojsoncxx`. You can serve or build the HTML version locally with the program `mkdocs`.
