### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by cbuchner1** [netheril96/StaticJSON#17]
Just some feature requests for your consideration:

1) would there be any interest in supporting the generation and parsing of enum types? The names of the enum could be mapped to std::string. A string not matching the enum type would cause a parsing error.

2) would it be feasible for StaticJSON to generate a JSON schema that defines what a valid JSON file has to look like?

**Comment by netheril96** [comment]
Both are interesting ideas. 

* For the first feature, it doesn't fit in the current interface of `add_property`. How do you propose the interface for adding enums looks like?

* I have little experience with json schema. I may be able to implement a generator, but I don't how to test it.

**Comment by cbuchner1** [comment]
Maybe a templated overload of the add_property function where you specify an enum type as template argument (this could be tested with std::is_enum) as well as a std::map (or boost::bimap?) to provide a mapping between the enum and their string representation:

template <class EnumType> void add_property(std::string name, EnumType* pointer, const std::map<EnumType, const std::string>&, unsigned flags_ = Flags::Default)

I have just started to evaluate StaticJSON as a possible replacement for autojsoncxx and I found that the support for from_document and to_document has disappeared. Any plans to bring this back? We perform some dynamic typing using autojsoncxx where we store some sections of the document as std::shared_ptr<rapidjson::Document> so we can later parse these parts in the constructors of objects as they are generated.

**Comment by cbuchner1** [comment]
I have added a code example to issue #17 [https://github.com/netheril96/StaticJSON/issues/17](url)
You will probably not get an email notification when I edit my comment, so I provide a quick link here.

**Comment by netheril96** [comment]
`Document` and json schema support have been implemented.

**Comment by cbuchner1** [comment]
Thank you very much. I will look into it ASAP

Christian



2016-07-22 15:16 GMT+02:00 Siyuan Ren <notifications@github.com>:

**Comment by cbuchner1** [comment]
Hi,

the support for rapidjson::Document works just fine fo rus.

Another feature suggestion:

Is it possible to support std::tuple<> as a container format? Use case

struct Edge
{
    std::string starting_node;
    std::string terminating_node;
    double speed_kmh;

    void staticjson_init(staticjson::ObjectHandler* h)
    {
        h->add_property("starting_node", &starting_node);
        h->add_property("ending_node", &ending_node);
        h->add_property("speed_kmh", &speed_kmh);
    }
};

struct Graph
{
    std::map<std::string, Edge> edges;

    void staticjson_init(staticjson::ObjectHandler* h)
    {
        h->add_property("edges", &edges);
    }
}

I serialize the edges of a graph like this, where each edge is associated with a unique ID (the std::string encoded in the "edges" map.  The drawback of this serialization is that each edge encodes the key names "starting_node", "ending_node" and "speed_kmh" in the JSON.

Can we instead do something like this where each edge gets serialized as a value-only JSON object like { "A", "B", 50.0 }   as compared to { "starting_node": "A", "ending_node": "B", "speed_kmh": 50.0 }

struct Graph
{
    std::map<std::string, std::tuple<std::string, std::string, double>> edges;

    void staticjson_init(staticjson::ObjectHandler* h)
    {
        h->add_property("edges", &edges);
    }
}

This would require std::tuple support in StaticJSON, I believe.

Is this feasible to add?

**Comment by netheril96** [comment]
StaticJSON used to be named autojsoncxx, which is harder to use due to the requirement of a code generator. During the rewrite, support for tuples are dropped because of the complexity of implementation. If you are interested, you can read the original implementation here https://github.com/netheril96/StaticJSON/blob/autojsoncxx/include/autojsoncxx/tuple_types.hpp. 

I am busy lately and probably won't implement tulle support in the coming months.

**Comment by netheril96** [comment]
Scratch that. I may implement it next week.

**Comment by netheril96** [comment]
Tuple support has been implemented.

Example

```c++
std::tuple<int, std::string, std::vector<double>> t;
std:: cout << to_pretty_json_string(t);
```

The parsing ignore extra elements and missing elements at the end, following the default behavior of the corresponding JSON schema.

**Comment by Lucretiel** [comment]
Here's a proposed implementation snippet for enum implementation.

    // The library provides something like this
    template<class EnumType> using EnumMapping = std::unordered_map<std::string, EnumType>
    template<class EnumType>
    class EnumHandler : public BaseHandler
    {
    private:
        const static EnumMapping enum_mapping;
        const static std::string enum_type_name;
        EnumType* m_value;
        
        // It'd be a fairly simple extension to make this case insensitive, though you'd
        // have to wrap EnumMapping.
        static bool load_enum(const std::string& value, EnumType& out)
        {
            if((auto found = enum_mapping.find(value)) != enum_mapping.end())
            {
                *m_value = found->second;
                return true;
            } else return false;
        }

    public:
        explicit EnumHandler(EnumType* v): m_value(v) {}

        bool String(const char* str, SizeType length, bool) override
        {
            if(!load_enum(std::string(str, length), *m_value))
               return set_some_error(...)
            this->parsed = true;
            return true;
        }

        // Also implement write, type_name, generate_schema. Pretty straightforward.
    };

    // Some helper macros
    #define ENUM_MAPPING(TYPE) const EnumMapping EnumHandler<TYPE>::enum_mapping
    #define ENUM_NAME(TYPE) const std::string EnumHandler<TYPE>::enum_type_name

    // AND THEN THE USER CAN WRITE THIS
    enum class Suit { heart, diamond, club, spade };

    template<>
    class Handler<Suit> : public EnumHandler<Suit> {};

    ENUM_MAPPING(Suit) = {
        {"heart", Suit::heart},
        {"diamond", Suit::diamond}
        {"club", Suit::club},
        {"spade", Suit::spade},
    };
    ENUM_NAME(Suit) = "Suit";

While we're here, we could also generalize EnumHandler a bit, with a FromString type that converts strings to user classes:

    template<class FromStringType>
    class FromStringHandler : public BaseHandler
    {
    private:
        virtual bool from_string(const string& value, FromStringType& out) =0;
        FromStringType* m_value;

    public:
        explicit FromStringHandler(FromStringType* v): m_value(v) {}

        bool String(const char* str, SizeType length, bool) override
        {
            if(!this->from_string(std::string(str, length), *m_value))
                return false;  // Set some error
            this->parsed = true;
            return true;
        }
    };

It's probably worth noting that the template-static trick used here could probably also be used with some of the other Handlers in StaticJSON (notably ObjectHandler), to prevent having to initialize the `unordered_map` every time you want to load a new object. You could use the obscure pointer-to-member feature (described [here](http://stackoverflow.com/questions/670734/c-pointer-to-class-data-member)) to implement such a map.

**Comment by netheril96** [comment]
Won't that macro define multiple instances of class static variable if used in a header file?

**Comment by Lucretiel** [comment]
Ah, it might. I know that it's safe to initialize template statics in a header file, even if it's included more than once, but it may not be safe to initialize the statics of instantiated templates. There's probably some way around that involving a static function or dummy type parameter.

**Comment by netheril96** [comment]
Enumerations support is added. See the updated README for an example.

The implementation use a inline function around the static object. The C++ linking rules prohibit multiple instances of function local static variables, so such definition is safe.
