### ISSUE TITLE
overload from_json_string to support std::string

### ISSUE THREAD

**Issue by cinghiale** [netheril96/StaticJSON#18]
Since you updated rapidjson to 1.1.0 it's possible to take advantage of the new [api](https://github.com/miloyip/rapidjson/pull/553) to parse a `std::string` without converting it to a `char*`.

I can prepare a PR if you are ok with the idea

**Comment by netheril96** [comment]
Go ahead with the PR.

**Comment by netheril96** [comment]
The new API seems to works only with `Document`, not generic SAX interface.
