### ISSUE TITLE
64 bit compile fails on vs2015 Update 3

### ISSUE THREAD

**Issue by imtrobin** [netheril96/StaticJSON#22]
Using x86, it compiles fine, switch to x64, it fails to compile

**Comment by netheril96** [comment]
You need to provide a minimal example that demonstrate the problem. The test case compiles and runs just fine on my computer with VS2015 x64 with update 3.

**Comment by imtrobin** [comment]
This is my main file. Do you need whole project? It just with staticjson, c++ console
[main.zip](https://github.com/netheril96/StaticJSON/files/766025/main.zip)

**Comment by netheril96** [comment]
Fixed in c20a3cbe2d1318f7d9f92dadce525c3e39166b77.

**Comment by imtrobin** [comment]
thanks
