### ISSUE TITLE
can you please mention dependency on rapidjson

### ISSUE THREAD

**Issue by ng5** [netheril96/StaticJSON#25]
Hi, Can you please mention dependency on rapidjson in the documentation. I was on latest version of rapidjson installed separately via vcpkg(windows) or normal(linux), however it caused loads of link error and took me a while to figure it out. 

After I removed rapidjson folder from staticjson, everything worked correctly. Hopefully this will help some one.  If possible, please simply remove rapidjson folder and ask users to install separately. 

Thanks a lot for the library.

**Comment by netheril96** [comment]
Done.

**Comment by ng5** [comment]
thanks a lot!
