### ISSUE TITLE
Duplicate key in map

### ISSUE THREAD

**Issue by imtrobin** [netheril96/StaticJSON#33]
Hi, I'm testing with a map , I did not set AllowDuplicatekey, but it did not return an error. e.g the json has 3 items, but it read 2 sucessfully.

```
struct Map
{
  std::map <string, string>  m;

	void	staticjson_init (staticjson::ObjectHandler* h)
	{
		h->add_property ("Map", &m);
		h->set_flags (staticjson::Flags::DisallowUnknownKey);
	}
}
{
 "Map": 
 {
 "one": { "x":"onedata"},
 "two" : { "x":"twodata"},
 "two" : { "x":"this is not taken"}
 }
}
```

**Comment by netheril96** [comment]
`AllowDuplicateKey` only works for the keys of the object itself. `map` does not errors on duplicate key. `multimap` collects all duplicated ones.

**Comment by imtrobin** [comment]
ok noted, thanks.
