### ISSUE TITLE
Hints on implementing support for `std::optional<T>`

### ISSUE THREAD

**Issue by nshcat** [netheril96/StaticJSON#34]
Hello,
I am looking to implement support for C++17's  STL-type `std::optional<T>` in your library in order to better use it in one of my projects. Can you provide a rough outline of what needs to be done in order to support it? The currently available implementations for other STL types like deque are sadly not commented that well, which makes understanding the internals of your library a bit difficult.

Regards

**Comment by netheril96** [comment]
Just include `optional_support.hpp`. Only tested on clang though.

**Comment by nshcat** [comment]
Thanks, for some reason I missed that file.
