### ISSUE TITLE
[Feature request]Can we ignore the failed property in ObjectHandler.

### ISSUE THREAD

**Issue by heroboy** [netheril96/StaticJSON#40]
Ignore the failed property, leave it original value, and continue to process the rest ones. Maybe add another flag?

**Comment by netheril96** [comment]
What about map handlers and list handlers? There is no way to pass such flags to them. Besides, this goes against the whole meaning of this library, namely, strict checking.

**Comment by heroboy** [comment]
Consider the json is a config file edit by some person. When he miss typed some value, I don't want abandon the whole json file but reading it as much as possible.

**Comment by heroboy** [comment]
Or I may changed class member type in c++ side without changing the name, and still keep the json file usable.

**Comment by netheril96** [comment]
I don't want to support any of these kinds of use cases. There are too many ways a JSON file can go wrong, and guessing what it really means is a hard task.
