### ISSUE TITLE
shadow_type can't be JsonDocument.

### ISSUE THREAD

**Issue by heroboy** [netheril96/StaticJSON#41]
In ConversionHandler::reset();
```
void reset() override
    {
        internal.prepare_for_reuse();
        shadow = shadow_type();
    }
```
If `shadow_type` is `JsonDocument`, then internal will be `JSONHandler` which reference the `shadow.m_alloc`. And if you call ` shadow = shadow_type();`, it will destroy the `m_alloc` referenced by `internal`.

**Comment by netheril96** [comment]
Good catch. Fixed in 26479e5.
