### ISSUE TITLE
Using in Visual C++ Project

### ISSUE THREAD

**Issue by baylf2000** [netheril96/StaticJSON#42]
Apologies for the newb question, but I'm trying to utilise this in a VS 2017 project and I'm not quite sure how to do this.

As a relative beginner to C++, I've just been using vcpkg to add libraries (like RapidJSON) as needed which seems to work very well, but I can't do that in this case so I'm a bit stuck.

Is there any chance you could provide some tips for doing this? Perhaps even an ultra-simple Visual Studio example project?

Many thanks in advance.

**Comment by netheril96** [comment]
Copy the directory under `include` and the file under `src` to your project dir, and add them to your project.

For example, if all your project has is a `main.cpp` file, copy the files in this repo such that the project has

* main.cpp
* staticjson.cpp
* staticjson
  - basic.hpp
  - document.hpp
  - ......

**Comment by netheril96** [comment]
You could have other ways of organization if you know how to set up the include path.

**Comment by netheril96** [comment]
README.md includes instructions. You could also look at source files under `test/`.
