### ISSUE TITLE
Better error descrption

### ISSUE THREAD

**Issue by imtrobin** [netheril96/StaticJSON#43]
Hi, I was looking to get a better description of parsing error because it's hard to diagonse a big json file with offsets.  The descrption prints "Invalid escape character in string" but it does not tell you which item, only offsets. Is there a way to get more info? I see the ParseStatue m_stack is empty.

**Comment by netheril96** [comment]
Sorry, the JSON parsing error message comes directly `RapidJSON`. `StaticJSON` provides error message only when the JSON is valid but its schema does not match your spec. Your case is the first.
