### ISSUE TITLE
Flags:: DisallowUnknownKey sets Flags::Optional and Flags:: IgnoreRead also

### ISSUE THREAD

**Issue by syoyo** [netheril96/StaticJSON#44]
https://github.com/netheril96/StaticJSON/blob/master/include/staticjson/basic.hpp#L146

The value of `Flags:: DisallowUnknownKey` is set to `0x16`(`22` in decimal). `0x16` also set a bits for `Flags::Optional` and `Flags:: IgnoreRead`. This may trigger some logical error.

I think the value of flags are defined in exclusive manner,  so guess `0x10` is a correct value for `Flags:: DisallowUnknownKey`.

**Comment by netheril96** [comment]
Yes, you are correct. Can you file a pull request?

**Comment by syoyo** [comment]
Thank you. I have filed a PR > https://github.com/netheril96/StaticJSON/pull/46
