### ISSUE TITLE
Please consider adding support for package managers

### ISSUE THREAD

**Issue by parkertomatoes** [netheril96/StaticJSON#50]
Thank you for this excellent library.

However, this:

> Just drop the include and src directory into your own project 

means a lot of folks, including myself, can't really use it. Being able to manage and easily update dependencies is important, especially for a non-header-only library.

So, purely as a feature request and with the intention of making using StaticJSON more accessible, please consider either adding a:
  * vcpkg port: https://vcpkg.readthedocs.io/en/latest/about/faq/#can-i-contribute-a-new-library
 * or a Conan recipe: https://docs.conan.io/en/latest/creating_packages.html

Thanks

**Comment by malidiab** [comment]
+1
