### ISSUE TITLE
Got compile error on v1.0.0

### ISSUE THREAD

**Issue by zhaopeng2009** [netheril96/StaticJSON#54]
Tried to build v1.0.0 with gcc8, got below build error:
In file included from /opt/rh/devtoolset-8/root/usr/include/c++/8/string:52,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/locale_classes.h:40,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/ios_base.h:41,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/ios:42,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/ostream:38,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/iterator:64,
                 from /root/json_decode/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:48,
                 from /root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/basic.hpp:3,
                 from /root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/document.hpp:2,
                 from /root/json_decode/StaticJSON/StaticJSON-master/src/staticjson.cpp:1:
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h: In instantiation of ‘class std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >’:
/root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/basic.hpp:263:70:   required from here
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3106:63: error: no class template named ‘rebind’ in ‘class staticjson::mempool::PooledAllocator<char>’
       typedef typename _Alloc::template rebind<_CharT>::other _CharT_alloc_type;
                                                               ^~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3119:68: error: no class template named ‘rebind’ in ‘class staticjson::mempool::PooledAllocator<char>’
       typedef __gnu_cxx::__normal_iterator<pointer, basic_string>  iterator;
                                                                    ^~~~~~~~
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3121:61: error: no class template named ‘rebind’ in ‘class staticjson::mempool::PooledAllocator<char>’
                                                             const_iterator;
                                                             ^~~~~~~~~~~~~~
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3122:53: error: no class template named ‘rebind’ in ‘class staticjson::mempool::PooledAllocator<char>’
       typedef std::reverse_iterator<const_iterator> const_reverse_iterator;
                                                     ^~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3123:52: error: no class template named ‘rebind’ in ‘class staticjson::mempool::PooledAllocator<char>’
       typedef std::reverse_iterator<iterator>      reverse_iterator;
                                                    ^~~~~~~~~~~~~~~~
In file included from /root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/document.hpp:2,
                 from /root/json_decode/StaticJSON/StaticJSON-master/src/staticjson.cpp:1:
/root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/basic.hpp: In function ‘std::string staticjson::mempool::to_std_string(const String&)’:
/root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/basic.hpp:263:83: error: ‘const String’ {aka ‘const class std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >’} has no member named ‘size’
     inline std::string to_std_string(const String& str) { return {str.data(), str.size()}; }
                                                                                   ^~~~
/root/json_decode/StaticJSON/StaticJSON-master/include/staticjson/basic.hpp:263:89: error: could not convert ‘{(& str)->std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >::data(), <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::string’ {aka ‘std::basic_string<char>’}
     inline std::string to_std_string(const String& str) { return {str.data(), str.size()}; }
                                                                                         ^
/root/json_decode/StaticJSON/StaticJSON-master/src/staticjson.cpp: In member function ‘void staticjson::ObjectHandler::postinit()’:
/root/json_decode/StaticJSON/StaticJSON-master/src/staticjson.cpp:320:72: error: ‘const class std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >’ has no member named ‘size’
         max_string_size = std::max<size_t>(max_string_size, pair.first.size());
                                                                        ^~~~
/root/json_decode/StaticJSON/StaticJSON-master/src/staticjson.cpp:324:22: error: ‘using String = class std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >’ {aka ‘class std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >’} has no member named ‘reserve’; did you mean ‘reference’?

**Comment by netheril96** [comment]
The problem is likely a old libstdc++. What is your version? Can you try building against libc++ instead?

**Comment by zhaopeng2009** [comment]
Thanks.... 
This is my libstdc++ version:
bash-4.2#  strings /lib64/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
bash-4.2# /sbin/ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6
bash-4.2# ls -la /lib64/libstdc++.so.6
lrwxrwxrwx. 1 root root 19 Dec  8  2021 /lib64/libstdc++.so.6 -> libstdc++.so.6.0.19

**Comment by netheril96** [comment]
Can you try the following:

* `git pull`.
* `git switch broken_allocator`
* Build with macro `STATICJSON_ALLOCATOR_TRAITS_BROKEN` defined.

**Comment by zhaopeng2009** [comment]
Got new failure as below:
/home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp: In constructor ‘staticjson::ObjectHandler::ObjectHandler()’:
/home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:307:96: error: no matching function for call to ‘std::map<std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler, std::less<std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> > >, staticjson::mempool::PooledAllocator<std::pair<const std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler> > >::map(std::map<std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler, std::less<std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> > >, staticjson::mempool::PooledAllocator<std::pair<const std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler> > >::allocator_type)’
     , leavesStack(decltype(leavesStack)::container_type::allocator_type(&memory_pool_allocator))
                                                                                                ^
/home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:307:96: note: candidates are:
In file included from /usr/include/c++/4.8.2/map:61:0,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/basic.hpp:9,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/document.hpp:2,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:1:
/usr/include/c++/4.8.2/bits/stl_map.h:241:9: note: template<class _InputIterator> std::map<_Key, _Tp, _Compare, _Alloc>::map(_InputIterator, _InputIterator, const _Compare&, const allocator_type&)
         map(_InputIterator __first, _InputIterator __last,
         ^
/usr/include/c++/4.8.2/bits/stl_map.h:241:9: note:   template argument deduction/substitution failed:
/home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:307:96: note:   candidate expects 4 arguments, 1 provided
     , leavesStack(decltype(leavesStack)::container_type::allocator_type(&memory_pool_allocator))
                                                                                                ^
In file included from /usr/include/c++/4.8.2/map:61:0,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/basic.hpp:9,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/document.hpp:2,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:1:
/usr/include/c++/4.8.2/bits/stl_map.h:224:9: note: template<class _InputIterator> std::map<_Key, _Tp, _Compare, _Alloc>::map(_InputIterator, _InputIterator)
         map(_InputIterator __first, _InputIterator __last)
         ^
/usr/include/c++/4.8.2/bits/stl_map.h:224:9: note:   template argument deduction/substitution failed:
/home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:307:96: note:   candidate expects 2 arguments, 1 provided
     , leavesStack(decltype(leavesStack)::container_type::allocator_type(&memory_pool_allocator))
                                                                                                ^
In file included from /usr/include/c++/4.8.2/map:61:0,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/basic.hpp:9,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/include/staticjson/document.hpp:2,
                 from /home/root/build/StaticJSON/StaticJSON-broken_allocator/src/staticjson.cpp:1:
/usr/include/c++/4.8.2/bits/stl_map.h:206:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::map(std::initializer_list<std::pair<const _Key, _Tp> >, const _Compare&, const allocator_type&) [with _Key = std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >; _Tp = staticjson::ObjectHandler::FlaggedHandler; _Compare = std::less<std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> > >; _Alloc = staticjson::mempool::PooledAllocator<std::pair<const std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler> >; std::map<_Key, _Tp, _Compare, _Alloc>::allocator_type = staticjson::mempool::PooledAllocator<std::pair<const std::basic_string<char, std::char_traits<char>, staticjson::mempool::PooledAllocator<char> >, staticjson::ObjectHandler::FlaggedHandler> >]
       map(initializer_list<value_type> __l,

**Comment by netheril96** [comment]
Well, your libstdc++ is too old to be standards conforming. Please use an older release https://github.com/netheril96/StaticJSON/releases/tag/v0.9.0
